config/routes.rb
ChoreTracker::Application.routes.draw do

  # Generated routes for models
  resources :chores
  resources :tasks
  resources :children
  
  # Routes for authentication
  resources :users
  resources :sessions
  match 'user/edit' => 'users#edit', :as => :edit_current_user
  match 'signup' => 'users#new', :as => :signup
  match 'logout' => 'sessions#destroy', :as => :logout
  match 'login' => 'sessions#new', :as => :login
  
  # Setting default route
  root :to => 'chores#index'
  
end

app/models/child.rb
class Child < ActiveRecord::Base
  attr_accessible :active, :first_name, :last_name
  
  has_many :chores

  validates_presence_of :first_name, :last_name

  scope :alphabetical, order('last_name', 'first_name')
  scope :active, where('active = ?', true)

  def name
  return self.first_name + " " + self.last_name
end
end

app/models/chore.rb
class Chore < ActiveRecord::Base
  attr_accessible :child_id, :completed, :due_on, :task_id

  belongs_to :child
  belongs_to :task
  
  validates_presence_of :child_id, :due_on, :task_id
  validates_inclusion_of :completed, in: [false, true]
  validates_date :due_on

  scope :by_task, joins(:task).order('tasks.name')
  scope :chronological, order('due_on')
  scope :pending, where('completed = ?', false)
  scope :done, where('completed = ?', true)
  scope :upcoming, where('due_on >= ?', Date.today)
  scope :past, where('due_on < ?', Date.today)

  def status
  	if self.completed == true
  		return "Completed"
  	else
  		return "Pending"
  	end
  end

end

app/models/task.rb
class Task < ActiveRecord::Base
  attr_accessible :active, :name, :points
  
  has_many :chores
  validates_presence_of :name, :points
  validates_numericality_of :points, :only_integer => true, :greater_than => 0

  scope :alphabetical, order('name')
  scope :active, where('active = ?', true)
end

app/models/user.rb
class User < ActiveRecord::Base
  # new columns need to be added here to be writable through mass assignment
  attr_accessible :username, :email, :password, :password_confirmation

  attr_accessor :password
  before_save :prepare_password

  validates_presence_of :username
  validates_uniqueness_of :username, :email, :allow_blank => true
  validates_format_of :username, :with => /^[-\w\._@]+$/i, :allow_blank => true, :message => "should only contain letters, numbers, or .-_@"
  validates_format_of :email, :with => /^[-a-z0-9_+\.]+\@([-a-z0-9]+\.)+[a-z0-9]{2,4}$/i
  validates_presence_of :password, :on => :create
  validates_confirmation_of :password
  validates_length_of :password, :minimum => 4, :allow_blank => true

  # login can be either username or email address
  def self.authenticate(login, pass)
    user = find_by_username(login) || find_by_email(login)
    return user if user && user.password_hash == user.encrypt_password(pass)
  end

  def encrypt_password(pass)
    BCrypt::Engine.hash_secret(pass, password_salt)
  end

  private

  def prepare_password
    unless password.blank?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = encrypt_password(password)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include ControllerAuthentication
  protect_from_forgery
end

app/controllers/children_controller.rb
class ChildrenController < ApplicationController
  before_filter :login_required
  
  def index
    @children = Child.alphabetical.all
  end

  def show
    @child = Child.find(params[:id])
  end

  def new
    @child = Child.new
  end

  def edit
    @child = Child.find(params[:id])
  end

  def create
    @child = Child.new(params[:child])
    if @child.save
      redirect_to @child, notice: 'Child was successfully created.'
    else
      render action: "new"
    end
  end

  def update
    @child = Child.find(params[:id])
    if @child.update_attributes(params[:child])
      redirect_to @child, notice: 'Child was successfully updated.' 
    else
      render action: "edit" 
    end
  end

  def destroy
    @child = Child.find(params[:id])
    @child.destroy
  end
end

app/controllers/chores_controller.rb
class ChoresController < ApplicationController
  before_filter :login_required, :except => :index 

  def index
    @chores = Chore.chronological.by_task.all  end

  def show
    @chore = Chore.find(params[:id])
  end

  def new
    @chore = Chore.new
  end

  def edit
    @chore = Chore.find(params[:id])
  end

  def create
    @chore = Chore.new(params[:chore])
    if @chore.save
      redirect_to @chore, notice: 'Chore was successfully created.' 
    else
      render action: "new" 
    end
  end

  def update
    @chore = Chore.find(params[:id])
    if @chore.update_attributes(params[:chore])
      redirect_to @chore, notice: 'Chore was successfully updated.' 
    else
      render action: "edit" 
    end
  end

  def destroy
    @chore = Chore.find(params[:id])
    @chore.destroy
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.authenticate(params[:login], params[:password])
    if user
      session[:user_id] = user.id
      redirect_to_target_or_default root_url, :notice => "Logged in successfully."
    else
      flash.now[:alert] = "Invalid login or password."
      render :action => 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, :notice => "You have been logged out."
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_filter :login_required

  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def edit
    @task = Task.find(params[:id])
  end

  def create
    @task = Task.new(params[:task])
    if @task.save
      redirect_to @task, notice: 'Task was successfully created.' 
    else
      render action: "new"
    end
  end

  def update
    @task = Task.find(params[:id])
    if @task.update_attributes(params[:task])
      redirect_to @task, notice: 'Task was successfully updated.' 
    else
      render action: "edit" 
    end
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :login_required, :except => [:new, :create]

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_url, :notice => "Thank you for signing up! You are now logged in."
    else
      render :action => 'new'
    end
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    if @user.update_attributes(params[:user])
      redirect_to root_url, :notice => "Your profile has been updated."
    else
      render :action => 'edit'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/children_helper.rb
module ChildrenHelper
end

app/helpers/chores_helper.rb
module ChoresHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/children/_form.html.erb
<%= form_for(@child) do |f| %>
  <% if @child.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@child.errors.count, "error") %> prohibited this child from being saved:</h2>

      <ul>
      <% @child.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :active %><br />
    <%= f.check_box :active %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/children/edit.html.erb
<h1>Editing child</h1>

<%= render 'form' %>

<%= link_to 'Show', @child %> |
<%= link_to 'Back', children_path %>

app/views/children/index.html.erb
<table>
  <tr>
    <th width="120" align="left">First name</th>
    <th width="120" align="left">Last name</th>
    <th width="120">Active</th>
    <th></th>
  </tr>

<% @children.each do |child| %>
  <tr>
    <td><%= child.first_name %></td>
    <td><%= child.last_name %></td>
    <td align="center"><%= child.active ? "Yes" : "No" %></td>
    <td><%= link_to 'Edit', edit_child_path(child) %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Child', new_child_path %>

app/views/children/new.html.erb
<h1>New child</h1>

<%= render 'form' %>

<%= link_to 'Back', children_path %>

app/views/children/show.html.erb
<p>
  <b>First name:</b>
  <%= @child.first_name %>
</p>

<p>
  <b>Last name:</b>
  <%= @child.last_name %>
</p>

<p>
  <b>Active:</b>
  <%= @child.active %>
</p>


<%= link_to 'Edit', edit_child_path(@child) %> |
<%= link_to 'Back', children_path %>

app/views/chores/_form.html.erb
<%= form_for(@chore) do |f| %>
  <% if @chore.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@chore.errors.count, "error") %> prohibited this chore from being saved:</h2>

      <ul>
      <% @chore.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :child_id %><br />
    <%= f.collection_select :child_id, Child.alphabetical.active.all, :id, :name, :prompt => "Select child..." %>
  </div>
  <div class="field">
    <%= f.label :task_id %><br />
    <%= f.number_field :task_id %>
  </div>
  <div class="field">
    <%= f.label :due_on %><br />
    <%= f.date_select :due_on %>
  </div>
  <div class="field">
    <%= f.label :completed %><br />
    <%= f.check_box :completed %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/chores/edit.html.erb
<h1>Editing chore</h1>

<%= render 'form' %>

<%= link_to 'Show', @chore %> |
<%= link_to 'Back', chores_path %>

app/views/chores/index.html.erb
<table>
  <tr>
    <th width="125" align="left">Child</th>
    <th width="200" align="left">Task</th>
    <th width="75">Due on</th>
    <th width="125">Completed</th>
    <th></th>
  </tr>

<% @chores.each do |chore| %>
  <tr>
    <td><%= chore.child.name %></td>
    <td><%= chore.task.name %></td>
    <td align="center"><%= chore.due_on %></td>
    <td align="center"><%= chore.status %></td>
    <td><%= link_to 'Edit', edit_chore_path(chore) %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Chore', new_chore_path %>

app/views/chores/new.html.erb
<h1>New chore</h1>

<%= render 'form' %>

<%= link_to 'Back', chores_path %>

app/views/chores/show.html.erb
<p>
  <b>Child:</b>
  <%= @chore.child_id %>
</p>

<p>
  <b>Task:</b>
  <%= @chore.task_id %>
</p>

<p>
  <b>Due on:</b>
  <%= @chore.due_on %>
</p>

<p>
  <b>Completed:</b>
  <%= @chore.completed %>
</p>


<%= link_to 'Edit', edit_chore_path(@chore) %> |
<%= link_to 'Back', chores_path %>

app/views/layouts/application.html.erb
<html>
	<head>
		<meta http-equiv="Content-type" content="text/html; charset=utf-8">
		<title>ChoreTracker :: <%= controller.controller_name.capitalize %></title>
		<link rel="shortcut icon" href="/gc_favicon.ico" type="image/x-icon" />
	  <%= stylesheet_link_tag    "application", :media => "all" %>
	  <%= javascript_include_tag "application" %>
		<%= csrf_meta_tag %>
	</head>

	<body>
		<div id="wrap">
    	<div id="header">
				<%= link_to(image_tag('qu_vu.jpg'), chores_path) %>
			</div>
			<br />
       <div id="nav">
       	<ul>
          <!-- OPTIONS FOR EVERYONE -->
        	<li><%= link_to 'Children', children_path %></li>
					<li><%= link_to 'Chores', chores_path %></li>
					<li><%= link_to 'Tasks', tasks_path %></li>
					<% if logged_in? %>
					<li><%= link_to 'Logout', logout_path %></li>
					<% else %>
					<li><%= link_to 'Login', login_path %></li>
					<% end %>
				</ul>
      </div> <!-- end of nav div -->
			<div style="clear:both;"></div>
	    	<div id="body">
				<p style="color: green" id="notice"><%= flash[:notice] %></p>
				<%= yield %>
			</div> <!-- end of body div -->

		</div><!-- end of wrap div -->
	</body>
</html>

app/views/tasks/_form.html.erb
<%= form_for(@task) do |f| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% @task.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :points %><br />
    <%= f.number_field :points %>
  </div>
  <div class="field">
    <%= f.label :active %><br />
    <%= f.check_box :active %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<h1>Editing task</h1>

<%= render 'form' %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<table>
  <tr>
    <th width="120" align="left">Name</th>
    <th width="120" >Points</th>
    <th width="120">Active</th>
    <th></th>
  </tr>

<% @tasks.each do |task| %>
  <tr>
    <td><%= task.name %></td>
    <td align="center"><%= task.points %></td>
    <td align="center"><%= task.active %></td>
    <td><%= link_to 'Edit', edit_task_path(task) %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Task', new_task_path %>

app/views/tasks/new.html.erb
<h1>New task</h1>

<%= render 'form' %>

<%= link_to 'Back', tasks_path %>

app/views/tasks/show.html.erb
<p>
  <b>Name:</b>
  <%= @task.name %>
</p>

<p>
  <b>Points:</b>
  <%= @task.points %>
</p>

<p>
  <b>Active:</b>
  <%= @task.active %>
</p>


<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :username %><br />
    <%= f.text_field :username %>
  </p>
  <p>
    <%= f.label :email, "Email Address" %><br />
    <%= f.text_field :email %>
  </p>
  <p>
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </p>
  <p>
    <%= f.label :password_confirmation, "Confirm Password" %><br />
    <%= f.password_field :password_confirmation %>
  </p>
  <p><%= f.submit (@user.new_record? ? "Sign up" : "Update") %></p>
<% end %>

app/views/users/edit.html.erb
<%= render 'form' %>

app/views/users/new.html.erb
<p>Already have an account? <%= link_to "Log in", login_path %>.</p>

<%= render 'form' %>